// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPtkNn1g-OO-KSg49HkprIz3la3h_2Hdw',
    appId: '1:145111207624:web:3f6ae0fdd1a8c1270f1ffd',
    messagingSenderId: '145111207624',
    projectId: 'mambafasttracker',
    authDomain: 'mambafasttracker.firebaseapp.com',
    storageBucket: 'mambafasttracker.firebasestorage.app',
    measurementId: 'G-PYVEV5RWJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqMkfFJ4-eij2Xh_91SogXFLKlTi39bJQ',
    appId: '1:145111207624:android:a964464b858cc8d20f1ffd',
    messagingSenderId: '145111207624',
    projectId: 'mambafasttracker',
    storageBucket: 'mambafasttracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7D93o_3o1EGexCPaSXGV82AJ9nJOP_vU',
    appId: '1:145111207624:ios:e50eed9e22c7e1de0f1ffd',
    messagingSenderId: '145111207624',
    projectId: 'mambafasttracker',
    storageBucket: 'mambafasttracker.firebasestorage.app',
    iosBundleId: 'com.example.mambaFastTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7D93o_3o1EGexCPaSXGV82AJ9nJOP_vU',
    appId: '1:145111207624:ios:e50eed9e22c7e1de0f1ffd',
    messagingSenderId: '145111207624',
    projectId: 'mambafasttracker',
    storageBucket: 'mambafasttracker.firebasestorage.app',
    iosBundleId: 'com.example.mambaFastTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPtkNn1g-OO-KSg49HkprIz3la3h_2Hdw',
    appId: '1:145111207624:web:9ff190d00283754f0f1ffd',
    messagingSenderId: '145111207624',
    projectId: 'mambafasttracker',
    authDomain: 'mambafasttracker.firebaseapp.com',
    storageBucket: 'mambafasttracker.firebasestorage.app',
    measurementId: 'G-5NXF7VJJ55',
  );

}